print("Welcome to your test mother.")
input("What year were you born in? ")
input("What is everyones name in the house including the animals? ")
input("what is your favorite color? ")
input("What is the your favorite thing to do? ")
input("Where does Ja Lisa live exactly? ")
input("What is everyones favorite thing to do? ")
input("Who is the two furries in the house? ")
input("What is DaVonte's favorite show? ")
input("What does Hunter likes to make all the time? ")
input("What is Tyesha's friend called? ")
input("What is the bill of rights? ")
input("What is the 39th president? ")
input("What 1*1/1+1-1? ")
input("What is the game does Davonte like two play? ")
input("How many animals are in the house? ")
input("What show does Nikita likes to watch? ")
input("In 1990, a person is 15 years old. In 1995, that person is 10 years old. how can this be.   ")
input('What is the color of the sky? ')
input("What is the color of the clouds? ")
input("what is the color of the ground? ")
print("Happy Valentine's Day")
print(100 * 100)
